- README.rst
- requirements.txt
- setup.py
This prevents us from running into conflicts with the installed requirements in edx-platform. I think we only want to call out a version when we know we need a specific version. Specifically, oauthlib==1.0.3 was conflicting with the version (oauthlib==0.7.2) that edx-platform installs.
> Do not pin dependency versions

- lti_consumer/lti_consumer.py
- lti_consumer/tests/unit/test_lti_consumer.py
- setup.py
Use django.utils.timezone.now() when determining if the due date of a component has passed to avoid tz-aware/naive datetime comparison stacktrace.
Related PR:
https://github.com/edx/edx-platform/pull/11270
> TNL-4046 Fix due date comparison bug

- lti_consumer/static/sass/student.scss
*Goal*
Adjusts the external resource button to be left aligned and visually separated from the supporting LTI text description. 
*Current*
*After Changes*
Note -
There is still separate work necessary to have this button use the correct base (new) edx-platform button styles, but that can be a separate edx-platform PR that adjusts the following area of styles: https://github.com/edx/edx-platform/blob/76b8e2e89761c30ac7aa2fa5e8aca4dc35d9002b/common/lib/xmodule/xmodule/css/lti/lti.scss
Review: @douglashall 
FYI - @scottrish - This doesn't address all of the changes we've talked about but it was a quick PR to get part of the way there.
> Visual styling for LTI external button

- lti_consumer/lti.py
- lti_consumer/tests/unit/test_lti.py
- setup.py
This is related to [LOC-78](https://openedx.atlassian.net/browse/LOC-78).
When using the edX LMS as a frontend for other LTI modules, this change enables us to transmit the user's preferred language setting (if present) as part of the POST request to set the iframe up.
If the user doesn't have a language set on their profile, or if they don't have an edX LMS profile set up, we won't transmit locale preferences, and the behavior will remain the same.
This PR is covered by the OpenCraft contributor agreement - thanks @antoviaque!
> Transmit launch_presentation_locale parameter

- lti_consumer/lti.py
- lti_consumer/tests/unit/test_lti.py
- setup.py
Fixes problems with #16 - we should now look at `language_proficiencies` to see if a single proficiency exists for us to use, rather than the defunct `language` attribute. I've also iterated the version number to 1.0.8.
> Fixing problems with #16's use of launch_presentation_locale

- lti_consumer/lti.py
- lti_consumer/tests/unit/test_lti.py
- setup.py
Reverts edx/xblock-lti-consumer#17
Sorry @haikuginger, I tested this after I merged and it was still not working. Turns out I was wrong about where we store the user's preferred language. The `openedx.core.djangoapps.user_api.models.UserPreference` is what we were looking for. You should be able to get the list of user preferences from the user object and filter by `key=pref-lang`. There should only ever be one UserPreference model with the key field set to pref-lang.
Please give this a manual test on your end next time.
> Revert "Fixing problems with #16's use of launch_presentation_locale"

- lti_consumer/lti.py
- lti_consumer/tests/unit/test_lti.py
- setup.py
@douglashall - I've updated the code and done manual testing to confirm that the `launch_presentation_locale` parameter is now being passed correctly per our conversation in #18 - sorry for the delay.
I used httpbin.org/post as the LTI target - that let me peek into the request parameters without needing to do any request sniffing.
> Fixing launch_presentation_locale (promise!); updating to v1.0.9

- lti_consumer/static/js/xblock_lti_consumer.js
There was some timing issues with dealing with keyboard navigation for LTI consumers using modal iframes on Firefox.
Based on [an answer on Stack Overflow](http://stackoverflow.com/questions/7046798/jquery-focus-fails-on-firefox) this is a solution that works on Firefox without breaking Chrome support.
Note: the iframed in LTI component doesn't work, but it should provide a real enough webpage for testing navigation. This should be tested in Firefox specifically. 
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
FYI: Tag anyone who might be interested in this PR here.
> Add workaround for Firefox focus issues.

- lti_consumer/lti_consumer.py
- lti_consumer/tests/unit/test_lti_consumer.py
This allows this xblock being hooked into get_course_lti_endpoints for
discovering LTI result/outcome endpoints.
**Background**: The old xmodule supports enumerates LTI endpoints so that they can be discovered and consumed by external tools. However, this functionality is missing when xmodule was refactored into xblock. Currently, only the old LTI xmodules can be discovered when /courses/COURSE_ID/lti_rest_endpoints/ is called. 
**Testing**:
- Create an LTI consumer component by following instructions here: http://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/exercises_tools/lti_component.html 
- Access htts://LMS_URL/courses/COURSE_ID/lti_rest_endpoints/
The endpoints for LTI component should be listed in JSON format.   
This PR is needed by …
> Add a compatibility function for get_course_lti_endpoints

- .travis.yml
- lti_consumer/lti_consumer.py
- lti_consumer/tests/unit/test_lti_consumer.py
- setup.py
Platform wants to control the editing the LTI fields from the studio for the course teams.
This PR does it by checking the configuration coming from the platform and decide if the editing of request username/email fields should be disabled or not.
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
FYI: Tag anyone who might be interested in this PR here.
> TNL-6688 – Control editing of request username/email fields from studio

- lti_consumer/lti.py
The module used for rebind was set to LtiConsumer instead of the xblock, which is wrong and causing an silent exception thrown and return 404 to the client without any indication of the cause.
To test it, follow the instruction here: https://github.com/edx/edx-tools/tree/master/lti/grades to setup a LtiConsumer and run the script to upload grade to a course. The script will failed at `_validate_lti_passport` because the silent exception thrown in `get_result` and 404 returned.
This is a critical issue because it crashes when someone uses LTI outcome service to retrieve the grade from the consumer.
> Fix the rebind exception when calling get_result

- lti_consumer/outcomes.py
- lti_consumer/tests/unit/test_outcomes.py
In this PR, any non-unicode string is first converted to unicode so it can be encoded successfully in [parse_grade_xml_body](https://github.com/edx/xblock-lti-consumer/blob/master/lti_consumer/outcomes.py#L23).
We need to do this because encoding is failed for strings (not specified as unicode) which have unicode chars. (When not specified as unicode, python 2.7.x use ASCII for encoding, unicode characters can not be encoded using ASCII).
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
> make system tolerant of ascii strings with unicode characters

- lti_consumer/templates/html/lti_iframe.html
- setup.py
Due to a chrome update some of our LTI blocks are broken in chrome. See documentation here: https://dev.chromium.org/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
FYI: @edx/educator-escalation
> Update iframe allowances for chrome v64

- .gitignore
- README.rst
- lti_consumer/lti.py
- lti_consumer/tests/unit/test_lti.py
- requirements.txt
- setup.py
- test_requirements.txt
https://openedx.atlassian.net/browse/EDUCATOR-2516
This:
* adds the `context_title` and `context_label` parameters to the set of params POSTed to an LTI provider
* adds a few missing requirements
* adds instructions to the README about running in docker devstack and testing against an LTI provider emulator.
> Add context_title and context_label parameters

- README.rst
- lti_consumer/lti.py
- lti_consumer/lti_consumer.py
- lti_consumer/tests/unit/test_lti.py
- lti_consumer/tests/unit/test_lti_consumer.py
- lti_consumer/tests/unit/test_utils.py
- setup.py
- test_requirements.txt
This pull request makes this XBlock extensible for adding parameters to the LTI provider in addition to the existing ones.
A customer needs `team` and `cohort` informaiton to be passed through the LTI channel to simplify integration with their LTI provider. At the same time we'd rather not fork the XBlock, so an Open-Closed model is needed.
I've added a couple of sections to `README.rst` to document specifying design and configuration steps of the new LTI parameter processors. Please check it out for more information about the changes that this pull request introduces.
I've written a package that we'll need to use for our customer to pass some personal user information in addition to the cohort and team info: https://github.com/appsembler/tahoe-lti/pull/1
* `XBLOCK_SETTINGS` are not …
> Allow plugins for the LTI XBlock to pass extra parameters to the provider

- lti_consumer/outcomes.py
- lti_consumer/tests/unit/test_outcomes.py
TypeError exception is raised by lti-consumer xblock because request body is not str type.
PROD-1119
> avoid-escape-exception

- lti_consumer/lti_consumer.py
- lti_consumer/tests/unit/test_lti_consumer.py
- setup.py
If a comment has `<img>` in the response it will not be rendered properly because it is escaped by `bleach`
Added `img` in safe tags so bleach will ignore `img`  so now <img> tag will renderd properly
> Added img to bleach safe tags

- lti_consumer/lti_consumer.py
- setup.py
Updated fragment import to remove deprecation warning to avoid unnecessary logs in Splunk
> Updated fragment import to remove depreciation warning

- lti_consumer/lti_consumer.py
- setup.py
This shows the 'problem' icon for LTI units, rather than the default 'other' icon.
https://openedx.atlassian.net/browse/AA-75
> Show graded unit icon

- lti_consumer/lti_consumer.py
- lti_consumer/static/js/xblock_studio_view.js
- lti_consumer/tests/unit/test_lti_consumer.py
This PR adds some javascript to conditionally hide LTI 1.1/1.3 fields depending on the selected version. This also improves the default value setting for LTI 1.3 secrets and removes the need of passing those to the frontend to be properly saved. 
**Jira tickets:** 
- https://openedx.atlassian.net/browse/TNL-7195
- https://openedx.atlassian.net/browse/OSPR-4463
f3fe0705520860e8e6868357a129c4a19cfe8e10: 
1. Add a `lti_consumer` block to a course.
2. Edit the block, check that LTI 1.3 fields are hidden.
3. Select LTI 1.3 on the version field, check that LTI 1.1 fields get hidden and LTI 1.3 are shown.
fed41f125532225aa157d74442cc01dfe1fa3fb7:
1. Add a `lti_consumer` block to a course.
2. Publish.
3. Go to LMS and check that the LTI 1.3 variables (`lti_1p3_client_id` …
> [BD-2] BB-2233: Conditionally hide Studio fields depending on LTI version

- lti_consumer/lti_consumer.py
This PR switches the usage of `runtime.user_id` by the external user id present in the latest XBlock runtime version.
**Testing instructions:** 
1. Using a test provider setup, install this branch.
2. Launch the IMS Global Reference tool.
3. Check that the user id received is not the Django ID, but the external user ID provided by the block runtime (using the `external_user_ids` app).
Detailed setup instructions here: https://github.com/edx/xblock-lti-consumer/pull/58
**Reviewer:**
> [BD-2] Switch to external user id.

- setup.py
The previous release did not include the LTI 1.3 packages.
> Include new packages in distribution

- setup.py
This is needed to include the `lti1p1` (etc) packages in the distribution.
> Find all packages in setup.py

- docs/decisions/0001-lti-extensions-plugin.rst
This PR adds an ADR to define the software architecture of the LTI consumer implementation in the platform.
The proposed approach, if implemented, will allow configuring and performing LTI launches anywhere in the platform, and have a consistent configuration storage for LTI related settings.
I've tried to follow the conventions from [this file](https://github.com/edx/frontend-app-learning/blob/master/docs/decisions/0001-record-architecture-decisions.rst) and linked documents. 
Feel free to leave comments on content and format of the ADR.
**Jira tickets:**
- https://openedx.atlassian.net/browse/TNL-7315
**Reviewers:**
> [BD-2] [BB-2612]: Add ADR to define LTI Plugin architecture implementation

- README.rst
- lti_consumer/lti_1p3/constants.py
- lti_consumer/lti_1p3/consumer.py
- lti_consumer/lti_1p3/tests/test_consumer.py
- lti_consumer/lti_xblock.py
- lti_consumer/tests/unit/test_lti_xblock.py
- lti_consumer/tests/unit/test_outcomes.py
- setup.py
Implement context claim on LTI1.3
**JIRA tickets**:
[OSPR-4795](https://openedx.atlassian.net/browse/OSPR-4795)
[TNL-7316](https://openedx.atlassian.net/browse/TNL-7316)
**Merge deadline**: None
1. Pull the `open-craft:patrick/BB-2516-lti-improvements-implement-context-claim-on-lti` branch locally.
2. Launch your LMS from the devstack with `make lms-shell`
3. Edit `/edx/etc/studio.yml` and ensure the `LTI_1P3_ENABLED` flag exists and is set to `true`:
```
FEATURE:
LTI_1P3_ENABLED: true
```
4. Follow instructions on the [README](https://github.com/open-craft/xblock-lti-consumer/tree/patrick/BB-2516-lti-improvements-implement-context-claim-on-lti#installing-in-docker-devstack) for installing the `xblock-lti-consumer` package
5. Install [`ngrok`](https://ngrok.com/) …
> [BD-24] [TNL-7316] Implement context claim on LTI 1.3

- lti_consumer/lti_xblock.py
- lti_consumer/tests/unit/test_lti_xblock.py
- setup.py
Make LTI Consumer Indexable
**JIRA tickets**: 
* https://openedx.atlassian.net/browse/TNL-6993
**Merge deadline**: "None"
1. Clone this repo in `src` directory of your devstacks.
2. Checkout this branch i.e `ahmed/bb-2706-make-lti-consumer-indexable`
3. Install the cloned project into both **LMS** and **Studio** by changing your directory to the `src/xblock-lti-consumer` directory in your devstack and executing `pip install -e .`
4. Add `lti_consumer` to the Advanced Module List. See https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/exercises_tools/lti_component.html#enabling-lti-components-for-a-course
5. Create a sample LTI Consumer Block.
6. Reindex your course.
7. Go to LMS and search for some string that appears in either the name or …
> [BD-29] [TNL-6993] [BB-2706] Make LTI Consumer indexable

- lti_consumer/lti_xblock.py
- lti_consumer/outcomes.py
- lti_consumer/tests/unit/test_lti_xblock.py
- lti_consumer/tests/unit/test_outcomes.py
- setup.py
This is just to keep it in line with other xblocks that define an is_past_due attribute. Nicer if they all have the same access pattern.
> Convert is_past_due to a method

- lti_consumer/lti_1p3/consumer.py
- lti_consumer/lti_1p3/exceptions.py
- lti_consumer/lti_1p3/key_handlers.py
- lti_consumer/lti_1p3/tests/test_consumer.py
- lti_consumer/lti_1p3/tests/test_key_handlers.py
- setup.py
This PR adds a few token verification mechanisms to support LTI Advantage services.
This is PR 2 of https://github.com/edx/xblock-lti-consumer/pull/92.
Currently there are no endpoints using this, so just make sure the code is same and checks are passing.
**Reviewer:**
> [BD-24] [TNL-7318]: BB-2355 - Add decoding and scope verification methods

- lti_consumer/static/js/xblock_lti_consumer.js
- lti_consumer/templates/html/student.html
- setup.py
Because the courseware microfrontend loads units inside iframes, the LTI modal ends up being squished and generally ugly.
This PR introduces a new message sent to the parent window to request a modal containing the contents of the LTI launch iframe.
[TNL-7410](https://openedx.atlassian.net/browse/TNL-7410)
> Send modal to parent window.

- NOTICE
- README.rst
- setup.py
We said Apache, and it is Apache, so why have a copy of AGPL?
> Correct the license copies

- lti_consumer/tests/unit/test_utils.py
I turned on coverage measurement of the tests (use "make covreport" to see the results). It showed that this code wasn't used.  Is it OK to remove it?
> This code isn't used?

- lti_consumer/lti_xblock.py
- lti_consumer/tests/unit/test_lti_xblock.py
Problem Statement:
We had a situation where we faced an issue with parsing the LTI passports because of extra colons in them.
LTI passports are parsed by using colon(:) as a delimiter. We were trying to integrate LTI content from Rustici controller, the key format of the provider is `content:<unit-no>:<id>` the LTI passport will like 
`<content_id>:content:<unit-no>:<provider_id>:<secret_key>`
So this results to throwing unformatted Key exception.
Hope this PR will fix that issue.
> Fixing extra colons in LTI key

- lti_consumer/lti_1p3/consumer.py
- lti_consumer/lti_1p3/exceptions.py
- lti_consumer/lti_1p3/extensions/rest_framework/authentication.py
- lti_consumer/lti_1p3/tests/extensions/rest_framework/test_authentication.py
- lti_consumer/plugin/urls.py
- requirements/constraints.txt
- requirements/test.in
- requirements/test.txt
- requirements/travis.txt
This PR adds an authentication class that's used by LTI extensions to check the JWT token and a Django router for LTI related viewsets.
Also includes a small fix (includes `iss` in LTI payload message).
**Testing instructions:**:
1. Checkout this branch.
2. Install requirements.
3. Make sure quality checks and tests are running properly.
4. There's no APIs using this currently, but it's well covered in tests.
**Notes:**
Split from https://github.com/edx/xblock-lti-consumer/pull/92 since it ended up growing too much.
**Reviewers:**
> [BD-24] [TNL-7318] BB-2355: Add LTI support and Django authentication extension. 

- lti_consumer/lti_1p3/constants.py
- lti_consumer/lti_1p3/tests/test_consumer.py
With this change, the IMS validation suite passes:
> Staff and instructors shouldn't have the Student role.

- lti_consumer/plugin/compat.py
- lti_consumer/plugin/views.py
- lti_consumer/tests/unit/plugin/test_views.py
- test.py
- test_settings.py
- test_urls.py
This PR changes a few settings and allows testing standalone Django endpoints from the plugin implementation.
This also adds basic testing to a few Django views that were missing coverage. 
1. Clone this repo.
2. Run tests.
3. Since some view related code changed, ideally you need to do a test launch, but since setting up LTI is not that easy, test one of the endpoints and make sure it's working.
_To test the keyset endpoint:_
1. Set this feature flag in Studio:
```
FEATURES:
LTI_1P3_ENABLED: true
```
2. Restart the LMS, create a course and add `lti_consumer` to advanced modules list.
3. Add the LTI Block, edit it, and set it to use LTI 1.3. Save.
4. Look at the preview in Studio, copy the Keyset URL and check that it works.
**Note:**
I've tested a full LTI …
> [BD-24][TNL-7580] BB-3010: Implement app view testing infrastructure

- README.rst
As stated by @giovannicimolin:
> 
>Due to a recent change in [Chrome](https://twitter.com/ChromiumDev/status/1293236234932846596) and [Firefox](https://hacks.mozilla.org/2020/08/changes-to-samesite-cookie-behavior/)
and the way they handle cookies, it’s not possible
to access cookies marked as ``SameSite=None`` if
they are not also Secure.
This is to help avoid a few CSRF attacks.
Secure cookies are only available when the request
is done through [HTTPS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) (see `Secure` attribute), which is not the case on
the devstack.
The workaround for this behaviour is to set
`DCS_SESSION_COOKIE_SAMESITE` from `'Lax'`
to `None` in the studio container's `devstack.py`,
when using tools such as `ngrok`.
This commit adds a note about …
> TNL-7608 - Add Note about ngrok usage.

- lti_consumer/models.py
- lti_consumer/plugin/compat.py
- lti_consumer/tests/unit/test_models.py
This PR fixes the block loading, previously we only loaded the descriptor, but to be able to bind back to a user to set grades, we need to load the block.
1. Checkout this branch.
2. Do a test launch, make sure it works.
3. Test rebinding a the block to a user. Run `make lms-shell`, then `./manage.py lms shell` and then run this code:
```
lti_config = LtiConfiguration.objects.get(pk=5)  # Adjust the PK here
user = User.objects.get(username='edx')
block = lti_config.block  
block.runtime.rebind_noauth_module_to_user(block, user)
```
**Reviewers:**
> [BD-24] [TNL-7661] [BB-3172] LTI Improvements - Load XBlock properly

- lti_consumer/admin.py
- lti_consumer/apps.py
- lti_consumer/lti_1p3/ags.py
- lti_consumer/lti_1p3/consumer.py
- lti_consumer/lti_1p3/tests/test_consumer.py
- lti_consumer/models.py
- lti_consumer/plugin/compat.py
- lti_consumer/signals.py
- lti_consumer/tests/unit/plugin/test_views_lti_ags.py
- lti_consumer/tests/unit/test_models.py
- lti_consumer/tests/unit/test_utils.py
- lti_consumer/utils.py
This PR adds support for the declarative grading model for LTI consumer.
**JIRA tickets**: 
- https://openedx.atlassian.net/browse/TNL-7661
~~**Discussions**:~~
**Dependencies**: None
~~**Screenshots**:~~
~~**Sandbox URL**:~~
**Merge deadline**: ASAP
1. Make sure lti_consumer installed as per [README.rst](https://github.com/edx/xblock-lti-consumer/blob/master/README.rst)
2. Setup a new LTI block with ``Scored = True`` and Set a ``weight`` value.
3. Test if the LTI launch is successful.
4. Go to admin ``/admin/lti_consumer/ltiagslineitem/`` URL and confirm that a Line Item has been generated automatically with correct LTI Configuration, resource id, label, and Maximum Score (``weight``).
5. Generate a JWT token -
- Go to www.jwt.io
- select RS-256
- Fill in both …
> [BD-24] [TNL-7661] [BB-3172] LTI Improvements - Use declarative grading model on XBlock launch

- README.rst
- setup.py
This PR changes ``xblock-lti-consumer`` version from ``2.3.2`` to ``2.4.0`` as part of previously merged PR #116 
**JIRA tickets**:  https://openedx.atlassian.net/browse/TNL-7661
**Discussions**: https://github.com/edx/xblock-lti-consumer/pull/116#issuecomment-734426488
**Dependencies**: None
~~**Screenshots**:~~ 
~~**Sandbox URL**:~~
**Merge deadline**: None
1. Check if the version changed from ``2.3.2`` to ``2.4.0`` in ``setup.py``.
**Author notes and concerns**:
N/A
**Reviewers**
~~**Settings**~~
> [BD-24] [TNL-7661] [BB-3172] Bump up the version

- lti_consumer/migrations/0005_migrate_keyset_to_model.py
otherwise this blows up, trying to migrate a record with no location
(the modulestore lookup throws).
Presumably this isn't (wasn't?) an issue in prod already, right?
But I did hit this in my devstack, having previously created an
LtiConfiguration record via Django Admin (without a location).
> Skip migration when no LTI XBlock location exists

- README.rst
- lti_consumer/migrations/0006_add_on_model_config_for_lti_1p1.py
- setup.py
[This](https://github.com/edx/xblock-lti-consumer/pull/130) previous PR added new fields to the `LtiConfiguration` model. One of the newly-added fields was a unique field with a default value. This case needs some [special handling](https://docs.djangoproject.com/en/2.2/howto/writing-migrations/#migrations-that-add-unique-fields) for migrations that the previous PR did not include. This PR adds proper handling for this so that migrations don't result in an error. 
**Merge deadline**: ASAP
1. If the migration from the previous PR was already applied, remove it by running `python manage.py lms migrate lti_consumer 0005`
2. Install lti-consumer-xblock==2.4.0 
3. Create an LtiConsumer object, it won't have a config_id value.
4. Run any pending migrations. 
5. Install …
> Fix migration `config_id` conflict.

- lti_consumer/lti_xblock.py
**Expect**: When an instructor enters invalid data, they can re-edit the component to enter valid data.
**Observe**: Instructor enters invalid data to the LTI, and the error message prevents any further editing. The only option is to delete the existing draft. 
1. In Studio as an instructor - create an LTI component.
2. Click Edit. Set either Modal Height or Modal Width to blank. Save.
3. View Error message: " WE'RE HAVING TROUBLE RENDERING YOUR COMPONENT
Students will not be able to access this component. Re-edit your component to fix the error"
Error: unsupported operand type(s) for -: 'int' and 'NoneType'
**Expect**: Option to edit the broken component exists. 
**Observe**: No edit option.
**Side note**: This also prompted feedback on the new microfrontend experience: It is AWESOME how …
> [TNL-7520] - Handle case when modal height and width and set to empty in LTI component in studio.

- lti_consumer/plugin/compat.py
- lti_consumer/plugin/urls.py
- lti_consumer/plugin/views.py
- lti_consumer/templates/html/lti-dl/render_dl_content.html
- lti_consumer/tests/unit/plugin/test_views_lti_deep_linking.py
This PR adds an endpoint for presenting/rendering Deep Linking Content. This PR depends on #127 
There are a couple of related PR's that should be reviewed and merged in the following order -
1. This PR
2. https://github.com/edx/xblock-lti-consumer/pull/131 - Implements ``link`` content type
3. https://github.com/edx/xblock-lti-consumer/pull/132 - Implements ``html`` content type
4. https://github.com/edx/xblock-lti-consumer/pull/133 - Implements ``image`` content type
**JIRA tickets**: 
https://tasks.opencraft.com/browse/BB-3374
~~**Discussions**:~~
**Dependencies**: None
~~**Screenshots**:~~
~~**Sandbox URL**:~~
**Merge deadline**: None 
1. Checkout this branch.
2. Set up a local LTI tool (recommended: https://github.com/dmitry-viskov/pylti1.3-django-example) …
> [BD-24] [BB-3374] LTI Deep Linking Content Presentation Endpoint

- README.rst
- lti_consumer/migrations/0008_fix_uuid_backfill.py
To correct the, in our case, single database entry that snuck in without
a UUID during the schema change.
Steps:
- Make the field editable
- Add `config_id` to all models missing it
- Make the field noneditable again
> fix: Migrate the UUID backfill again

- README.rst
- lti_consumer/api.py
- lti_consumer/lti_1p3/consumer.py
- lti_consumer/lti_1p3/extensions/rest_framework/serializers.py
- lti_consumer/lti_1p3/tests/test_consumer.py
- lti_consumer/lti_xblock.py
- lti_consumer/tests/unit/test_api.py
- lti_consumer/tests/unit/test_lti_xblock.py
- setup.py
This PR implements the base LTI Deep Linking content presentation for `ltiResourceLink` types.
68d9c510cba3b78490c48ce8fc83c9a4b0ba5481: contains the full code changes.
5973a4350416ff61bef4e2321685cfe38986b10f: adds tests to check functionality.
1. Checkout this branch.
2. Set up a local LTI tool (recommended: https://github.com/dmitry-viskov/pylti1.3-django-example) and ngrok tunnel.
3. Do a deep link launch (from Studio link).
5. Select an option in the LTI tool's UI.
6. Go to http://localhost:18000/admin/lti_consumer/ltidlcontentitem/ and check that the option you selected is stored in the model.
7. Go to the LMS and load the LTI section.
8. Check that the local tool opens with the configuration you've selected in step 5.
**Conformance testing:**
1. Set up LTI …
> [BD-24][TNL-7824][BB-3373]: Implement ltiResourceLink deep linking content presentation

- lti_consumer/migrations/0009_backfill-empty-string-config-id.py
The previous backfills handled NULL entries;
this handles empty strings.
The difficulty here was that since the empty string in an invalid UUID
(as opposed to None/NULL which is just "blank"), attempts to instantiate
models would fail, given the invalid data. This meant we couldn't use
the Django ORM to handle the migration entirely; we need to craft some
raw SQL to work-around these checks and limitations.
> fix: Manually backfill config_id UUIDs again

- lti_consumer/migrations/0010_backfill-empty-string-lti-config.py
- setup.py
The difficulty here is that the empty string in an invalid JSON
dictionary (as opposed to None/NULL or '{}' which is just "blank");
attempts to instantiate models would fail, given the invalid data. This
meant we couldn't use the Django ORM to handle the migration entirely;
we need to craft some raw SQL to work-around these checks and
limitations.
Related-To: 42a9e342ef57a9ffa5016f4f57da633a811d2c0f
Related-To: https://github.com/edx/xblock-lti-consumer/pull/144
> fix: Manually backfill lti_config dicts

- docs/decisions/0004-lti-advantage-nrps.rst
This PR adds an ADR to discuss the possible implementations of the LTI NRPS service.
Related PRs:
https://github.com/edx/xblock-lti-consumer/pull/124
https://github.com/edx/edx-platform/pull/25843
https://github.com/edx/edx-platform/pull/25844
@ormsbee Since you raised the scalability issue of the API.
@nedbat @shimulch
> [BD-24][TNL-7919] LTI Advantage Names and Roles provisioning service implementation direction

- lti_consumer/plugin/compat.py
- setup.py
Fall-back to the old path.
Once the LMS has fully switched over to this new path [1],
we can remove the legacy (LMS) import support here.
- [1] https://github.com/edx/edx-platform/pull/27289
> fix: Try importing LMS helper from new path

- docs/decisions/0003-lti-1p3-score-linking.rst
- docs/decisions/0005-lti-1p3-score-linking-improved.rst
- lti_consumer/lti_1p3/consumer.py
- lti_consumer/lti_1p3/extensions/rest_framework/utils.py
- lti_consumer/lti_xblock.py
- lti_consumer/models.py
- lti_consumer/plugin/views.py
- lti_consumer/signals.py
- lti_consumer/static/js/xblock_studio_view.js
- lti_consumer/tests/unit/plugin/test_views_lti_ags.py
- lti_consumer/tests/unit/test_models.py
This code re-enables the programmatic grade approach for LTI AGS and improves the grade publishing handling.
It includes:
- a11232f0081ab61836f8d3b3c9658259909af170: Adds support for `programmatic` approach and add option to XBlock settings.
- 56f5541b519f5b6b9bd78b005dba3960a0b6fac0: Improves grades handling and add more logs to the method.
- e85d696267b1eea5afc06a1001e49e39ad33f3d7: Adds a missing test for the `Score` model.
- b39aba40073fbe8f5ed3e7ef949d79dc3e25e996: ADR changing the previous decision.
I'm trying to use the new [OEP-51](https://open-edx-proposals.readthedocs.io/en/latest/oep-0051-bp-conventional-commits.html) for the commits, any feedback is welcome.
a11232f0081ab61836f8d3b3c9658259909af170 - Programmatic scores:
1. Set up a test LTI tool that …
> [BD-24][TNL-8158] BB-3862: LTI AGS Programmatic grades support & documentation improvements

- lti_consumer/api.py
- lti_consumer/lti_1p3/consumer.py
- lti_consumer/lti_xblock.py
This PR fixes two small issues found when going through the updated documentation steps:
- e3fe63a: Minor compatibility fix, some tools assume `aud` is a plain text string instead of a list. 
- b288707: Fix deep linking studio view introduced by https://github.com/edx/xblock-lti-consumer/pull/149 and the interaction of `[]` with [the django template](https://github.com/edx/xblock-lti-consumer/blob/master/lti_consumer/templates/html/lti_1p3_studio.html#L370).
- 1b402ee: Add the missing `lti_advantage_ags_mode` to the `hide_fields` setting.
**Testing instructions for 1b402ee:**
1. Checkout `master` branch on your devstack and install.
3. Add `lti_consumer` to a course advanced module list.
4. Add an lti consumer into the course and click **Edit**.
6. You'll see the `LTI Assignment and …
> [BD-24] Minor fixes found while testing documentation

- docs/decisions/0005-lti-pii-sharing-flag.rst
This ADR proposes that we use the existing CourseEditLTIFieldsEnabledFlag
for LTI Course tabs in addition LTI XBlocks, and move it to this repo as
intended via EDUCATOR-121.
> docs: ADR to decide the future of the CourseEditLTIFieldsEnabledFlag [BD-03] [TNL-7945]

- Makefile
- requirements/common_constraints.txt
- requirements/constraints.txt
so that dependabot can access the constraints file and automatically
create security PRs; it fails if the constraints file is specified via
remote URL.
> build: save common_constraints.txt locally

- README.rst
- lti_consumer/lti_xblock.py
- setup.py
Added multi device support on student_view using xblock.supports
Edx mobile team has been working on this [epic](https://openedx.atlassian.net/browse/LEARNER-8350) Open xBlocks in the Browser. To show xblock on mobile browser xblock needs to send student_view_multi_device as true. Therefore I have added its support.
A similar PR for word cloud xblock:
https://github.com/edx/edx-platform/pull/27386/files
Jira Ticket: https://openedx.atlassian.net/browse/LEARNER-8413
Learner-8413
> feat: Added multi device support on student_view

- lti_consumer/lti_1p1/consumer.py
- lti_consumer/lti_xblock.py
- setup.py
Somewhere between versions 2.0.0 and 2.1.0, the code to handle external parameter processors was dropped. This PR adds it back. Without this, external processors that are specified in the [parameter processors settings](https://github.com/edx/xblock-lti-consumer#configuring-the-parameter-processors-settings) is not called.
**Jira Tickets:**  [OSPR-5686](https://openedx.atlassian.net/browse/OSPR-5686)
**Sandbox URL:** TBD
**Testing Instructions:**
1. Install this branch on your xblock runtime environment (for example xblock-sdk).
2. Test the parameter processors from tahoe-lti as per the [test instructions provided](https://github.com/appsembler/tahoe-lti#development-guide)
3. Verify that the external parameter processors are being called correctly.
**Reviewers**
> [SE-4235] Add missing parameter processors code

- test.py
The test suite was generating error log messages when tests would cause
error conditions.  This cluttered the output needlessly, because it
looked like test failures, but were actually tests succeeding.  Now all
log messages are suppresed during the test suite.
In addition, the XBlock runtime generates a warning about needing
IdGenerator in the future.  I'm suppressing this warning also.
Now the test suite just outputs 397 nice dots.
> test: suppress noise

- README.rst
- lti_consumer/static/js/xblock_lti_consumer.js
For [TNL-8584](https://openedx.atlassian.net/wiki/spaces/PT/pages/3221028876/TNL-8584+Discovery+Long-term+fix+for+cross-origin+iFrames) I need to make a proof of concept of a "Open resource in new window" modal dialog. 
Context: Our current LTI Component XBlock provides an option to "View resource in a New Window", which uses JS to launch a new window/tab. These capabilities were removed in Chrome v92. Here's some referances to those changes: TL;DR: there is a temporary cookie workaround, but this problem also started occurring on Safari 15. 
https://developer.chrome.com/origintrials/#/view_trial/2541156089743802369
. Chrome provided a temporary work-around which we now use in production. But we now need to design and implement a longer term fix.
These issues have since migrated to …
> fix: Long-term fix for cross-origin iFrames

- README.rst
- lti_consumer/__init__.py
Upon inspecting [#207](https://github.com/edx/xblock-lti-consumer/commit/133d3e9b7e5a9647c48aa8dd82886cfa1b437f31#:~:text=Merge%20pull%20request-,%23204,-from%20edx/fix) The change-logs did not reflect the move from 3.0.0 to 3.1.0. These changes makes that cklear that that information is missing, while also bumping up the version to reflect LTI changes.
> docs: reflect changes in changelog and version

- README.rst
- lti_consumer/__init__.py
- lti_consumer/lti_xblock.py
- lti_consumer/tests/unit/test_lti_xblock.py
- lti_consumer/utils.py
This PR adds the capability to add custom parameter template values in order to be substituted by a processor.
We must have the following configuration in order to make this happen
- Add the following settings variable to map our template values with their corresponding processors. Also, these processors must return a string object.
`LTI_CUSTOM_PARAM_TEMPLATES = { 'templated_param_value': 'customer_package.module:func' }`
- In Studio we will have the custom parameters field value such as:
`["static_param=static_value", "dynamic_custom_param=${templated_param_value}"]`
**Note.** It must be wrapped by **${** and  **}** to indicate it is a templated_value to substitute.
I want to be able to set dynamic custom parameters in the LTI consumer Xblock in Studio so that dynamic value should be …
> feat: custom parameters template substitution.

- lti_consumer/__init__.py
Version 3.3.0 has already been released on PyPi but it was never updated here in that PR and hence there was inconsistency in the version number leading to wrong version bump in the successive PRs. This PR fixes the issue with the version number
> Fix Version Number

- README.rst
- lti_consumer/__init__.py
- lti_consumer/lti_1p1/contrib/django.py
- lti_consumer/lti_1p1/contrib/tests/test_django.py
This fixes template rendering for LTI 1.1 embeds.
**Reviewers:**
> fix: Fix LTI 1.1 template rendering on LTI 1.1 embeds

- README.rst
- lti_consumer/__init__.py
- lti_consumer/lti_xblock.py
- lti_consumer/tests/unit/test_lti_xblock.py
This PR fixes content being launched after deep linking with H5P.
1. Set up a H5P integration using LTI 1.3
2. Set up Deep Linking.
3. Run a deep linking request (if you run into permission issues, comment out [this line](https://github.com/openedx/xblock-lti-consumer/blob/master/lti_consumer/plugin/views.py#L195) if testing locally).
4. Go to the LMS and check that H5P content is successfully launched.
**Validation testing:**
@schenedx Can you run the LTI validation tool with these recent changes? It needs to run the entire conformance suite so we know this isn't out of the spec.
**Notes:**
- This doesn't fix the LTI Deep Linking flow permission issues raised in this thread: https://openedx.slack.com/archives/C0GR05YC9/p1644575271361139
**Reviewer:**
> fix: LTI Deep linking launch parameter for H5P WIP

- README.rst
- lti_consumer/__init__.py
- lti_consumer/plugin/compat.py
- lti_consumer/plugin/views.py
- lti_consumer/tests/unit/plugin/test_views_lti_deep_linking.py
This PR fixes a permissions check issue when saving Deep Linking content edits back into Studio. This was caused by the incorrect API being used causing it to error out when any user other than a superuser was used.
We're basically replacing the old check with a new call to Studio's `has_studio_write_access` with the right parameters.
_Testing instructions written to members with access to H5P testing tools._
Before following these instructions, make sure you have a publicly accessible devstack set up (instructions [here](https://github.com/openedx/xblock-lti-consumer#lti-13) - ignore the LTI tool setup steps).
1. Set up a LTI 1.3 integration on H5P (from H5P dashboard: `Manage organization` -> `Connect LMS`).
2. Add a new LTI consumer block in your devstack and …
> FAL-2844: Fix LTI Deep Linking permissions issues

- README.rst
- lti_consumer/__init__.py
- lti_consumer/lti_xblock.py
- lti_consumer/tests/unit/test_lti_xblock.py
Fixes #237 
- Changes `render_mako_template` -> `render_django_template` in `lti_1p3_launch_callback` exception handlers
- Check that `% trans` is not in response bodies so we know template was properly rendered
> 237 lti 1p3 launch permission templates not rendered

- lti_consumer/__init__.py
- lti_consumer/plugin/compat.py
This update caused by removing support for the LegacyWaffle* classes.
See https://github.com/openedx/public-engineering/issues/28 for details.
> FC-0001: use modern waffle flag syntax

- lti_consumer/plugin/compat.py
Rename toggle_warnings to toggle_warning for consistency with setting_warning.
Relates to: https://github.com/openedx/code-annotations/pull/80
> FC-0001: rename toggle_warnings to toggle_warning

- requirements/pip_tools.txt
This commit upgrades the version of pip-tools used in this repository from `6.6.0` to `6.6.2`.
In version `6.6.0` of `pip-tools`, there is a bug that is preventing `pip-tools` from working. This is breaking the Python requirements update GitHub action in this repository.
The error is `ImportError: cannot import name 'BAR_TYPES' from 'pip._internal.cli.progress_bars'`. The error was reported [here](https://github.com/jazzband/pip-tools/issues/1617). The fix to this bug was released in version `6.6.2` of `pip-tools`. See the comment [here](https://github.com/jazzband/pip-tools/issues/1617#issuecomment-1126245586).
Version `6.6.1` of `pip-tools` also has a bug, which is fixed in version `6.6.2`. I observed this issue breaking the Python requirements update GitHub action in another …
> fix: upgrade pip-tools to fix bug in versions 6.6.0 and 6.6.1

- README.rst
- lti_consumer/__init__.py
- lti_consumer/lti_1p1/contrib/django.py
- lti_consumer/lti_1p1/contrib/tests/test_django.py
- lti_consumer/lti_xblock.py
- lti_consumer/plugin/compat.py
- lti_consumer/tests/unit/test_lti_xblock.py
- lti_consumer/track.py
- lti_consumer/utils.py
Track lti launch request events with the LMS event tracking library. This should fail silently if used outside the LMS.
> feat: add event tracking to lti launch

- README.rst
- lti_consumer/__init__.py
- lti_consumer/lti_1p3/extensions/rest_framework/authentication.py
Modified the Lti1p3ApiAuthentication authentication backend to return
AnonymousUser instead of None. This allows DarkLangMiddleware to work
properly without crashing when middleware tries to get a user info
from the request.
This investigation and patch was originally done by @OlhaShyliaieva in:
https://github.com/openedx/xblock-lti-consumer/pull/228
I'm just rebasing it onto the latest version to land this change.
> fix: Change user from None to AnonymousUser in authenticated requests

- lti_consumer/__init__.py
- lti_consumer/lti_xblock.py
This commit adds supplemental logging to diagnose the bug reported in [MST-1540](https://2u-internal.atlassian.net/browse/MST-1540). The bug is that learners are encountering the `LtiError` when trying to do an LTI launch. The learners appear to be authenticated, so this error should not occur. The bug is not easily reproducible in production or development, so this supplemental logging is added to help understand the user's state when the error is raised.
The current hypothesis is that user is temporarily represented by the AnonymousUser in the request that is made when doing the LTI launch, despite the user otherwise being authenticated. Logging in Splunk suggests that this is the case, because logs are of the following form, 
`2022-07-22 15:10:14,214 ERROR 5067 [django.request] [user …
> test: add debugging log statements for user_id LtiError

- lti_consumer/__init__.py
- lti_consumer/lti_1p3/consumer.py
- lti_consumer/lti_1p3/exceptions.py
- lti_consumer/lti_1p3/key_handlers.py
- lti_consumer/lti_xblock.py
The error handler in `LtiConsumerXBlock.lti_1p3_launch_callback` logs a warning when a select set of exceptions are handled. That log does not contain useful information about the nature of the exception, because the exceptions were not being instantiated with error messages. The try...catch is a large block that contains code that can raise a multitude of errors, so these changes will enable better debugging.
This commit:
* adds helpful messages to the raised exceptions.
* adds the `exc_info=True` argument to include the stack trace of the handled exception.
* adds `ValueError` and `TypeError` to the list of handled exceptions, because the code can raise exceptions of these types.
This is a sample log before.
```
2022-08-01 21:26:51,992 WARNING 5544 [lti_consumer.lti_xblock] [user 3] [ip …
```
> fix: missing exception details in logs

- lti_consumer/__init__.py
- lti_consumer/lti_xblock.py
- lti_consumer/plugin/views.py
- lti_consumer/templates/html/lti_launch_error.html
- lti_consumer/tests/unit/plugin/test_views.py
- lti_consumer/tests/unit/test_lti_xblock.py
[[MST-1585]](https://2u-internal.atlassian.net/browse/MST-1585)
**Description**
In the LTI 1.1 launch handler, we set the user context, including the `user_id`. We do this by calling to the LMS's `DjangoXBlockUserService` to get information about the user. Sometimes, the user is unauthenticated. Sometimes, this is because the user is a web crawler. Other times, the user is a real user, but we do not know why the user is unauthenticated. We have some theories, but we have been unable to confirm them. Regardless, we should not surface a 500 error to the user.
This pull request adds handling for the `LtiError` that is raised when a user is unauthenticated during an LTI 1.1 launch. It catches the `LtiError` and renders an error page. The error page that was used for LTI 1.3 launches, formerly …
> Handle LtiError Error During LTI 1.1 Launch for Unauthenticated User

- catalog-info.yml
Turns out we can't use spaces here
> fix: catalog-info syntax

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/plugin/views.py
This commit fixes a bug caused by the `X-Frame-Options` response header. The `X-Frame-Options` response header indicates to the browser whether a site's content can be loaded within certain tags, including the <iframe> tag. This is a form of clickjacking protection.
In Django, this response header is set by the `django.middleware.clickjacking.XFrameOptionsMiddleware` middleware. In the edx-platform, by default, `X-Frame-Options` is set to DENY (see the `X_FRAME_OPTIONS` Django setting), which means that the response content returned by Django views cannot be loaded within certain tags. However, this behavior can be disabled by decorating views with the `django.views.decorators.clickjacking.xframe_options_exempt` view decorator.
This creates a problem for LTI 1.3 launches in the …
> LTI 1.3 Fixes: Clickjacking Protection Preventing Launch and Incorrect Authentication Response/Launch URL

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/api.py
- lti_consumer/lti_xblock.py
- lti_consumer/models.py
- lti_consumer/plugin/compat.py
- lti_consumer/signals.py
- lti_consumer/templatetags/get_dl_lti_launch_url.py
- lti_consumer/tests/unit/plugin/test_views.py
- lti_consumer/tests/unit/plugin/test_views_lti_ags.py
- lti_consumer/tests/unit/plugin/test_views_lti_deep_linking.py
- lti_consumer/tests/unit/test_api.py
- lti_consumer/tests/unit/test_lti_xblock.py
- lti_consumer/tests/unit/test_models.py
Includes an improvement to anonymous loading because we're going to be using block load all the time for configs stored on the xblock. Basically if the block has already been loaded and bound to a user be happy and leave it. And if the block needs to be loaded and you have a user, load as that user. Only fall through to anonymous user when you have no other option (for example when being called by the LTI provider directly which is not a user).
There are a few cleanup diffs, the only interesting one is that codecov complained about compat so I added pragmas to document our lack of compat tests. The amount of mocking required would make those basically worthless.
> API gets config from launch data via config_id

- lti_consumer/utils.py
... without messing up the rest of your world by changing the LMS base URL for everyone. Meant for ngrok testing of LTI 1.3.
> feat: add override for the LMS_BASE_URL in various LTI settings

- docs/decisions/0007-lti-launch-decoupling.rst
This commit adds an ADR describing our strategy for decoupling LTI launches from the XBlock and from the edX platform.
> Add ADR for decoupling LTI launches from the XBlock

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/api.py
- lti_consumer/models.py
- lti_consumer/plugin/compat.py
- lti_consumer/plugin/views.py
- lti_consumer/tests/unit/plugin/test_views.py
- lti_consumer/tests/unit/plugin/test_views_lti_ags.py
- lti_consumer/tests/unit/plugin/test_views_lti_deep_linking.py
- lti_consumer/tests/unit/plugin/test_views_lti_nrps.py
- lti_consumer/tests/unit/test_api.py
- lti_consumer/tests/unit/test_lti_xblock.py
- lti_consumer/tests/unit/test_models.py
For the config model we do not need to go as far as binding the block to the user and already get enough data out of the modulestore to satisfy the storage on the xblock case. Add a new function to get that much xblock only.
For the limited cases where we are using the block more directly as a block we maintain the old function.
Also includes a fix to test_views that was closing the wrong level mock and leaving an open patch into other tests.
The behavior we are fixing is described in https://2u-internal.atlassian.net/browse/MST-1697 - basically, the weird compat.load_block_as_user squirrels its way into LMS specific block loading and binding code and that does not work in Studio. Before version 6, we got away with it because we mostly asked for the config by saying …
> fix: remove general use of load_block_as_user

- lti_consumer/__init__.py
I forgot to update the version number in the `__init__.py` in #297 during a rebase, which is preventing me from releasing the changes. This corrects the version number.
> build: update library version to 6.2.0 to release changes in pull #297

- CHANGELOG.rst
- lti_consumer/__init__.py
I made a mistake and published a release and created a tag for a `6.2.0` release without updating the library version in `__init__.py`. After correcting the version number, I couldn't publish a corrected release to PyPI because the `6.2.0` tag was associated with the commit before the commit with the updated version number. Instead of mucking around with pushing modified tags, I'm going to skip to the `6.3.0` tag instead.
> build: update library version to 6.3.0 to release changes in pull #297

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/lti_xblock.py
- lti_consumer/plugin/compat.py
- lti_consumer/tests/unit/test_lti_xblock.py
- lti_consumer/utils.py
JIRA: [MST-1717](https://2u-internal.atlassian.net/browse/MST-1717)
This commit introduces a new `CourseWaffleFlag` `lti_consumer.enable_external_user_id_1p1_launches`. When this flag is enabled for a course, LTI 1.1 XBlock launches in that course will send the user's `external_user_id` as the `user_id` attribute of the launch. `external_user_id` is the user's external user ID as defined, created, and stored by the `external_user_ids` Djangoapp in the edx-platform. When this waffle is not enabled for a course - the default case - LTI 1.1 XBlock launches in that course will continue to send the user's `anonymous_user_id` as the `user_id` attribute of the launch, as before.
This provides an opt-in opportunity for courses to send a consistent, static, and opaque user identifier in an LTI 1.1 …
> Add course flag to send external_user_id as user_id in LTI 1.1 XBlock launches

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/models.py
The block is not loadable in exams so clean fails in that IDA, but we shouldn't need the block to ask a question about the course.
Validated locally by editing configs in admin and observing that it knows the course ID from the location and uses it to look up the waffle flag.
> fix: do not attempt to load the block just to look at the location

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/lti_xblock.py
- lti_consumer/outcomes.py
- lti_consumer/tests/unit/test_lti_xblock.py
- lti_consumer/tests/unit/test_outcomes.py
In https://github.com/openedx/xblock-lti-consumer/pull/307, we added the ability to send a stable, static user identifier (i.e. external user ID) to fix failed launches with the QwikLabs tool. This is because the QwikLabs tool did not work with the course-anonymized user IDs we used to send (i.e. anonymous user IDs). Inadvertently, this change broke the LTI 1.1 Basic Outcomes Service and the LTI 2.0 Result Service for courses that use the external user ID (i.e. they have the `lti_consumer.enable_external_user_id_1p1_launches` `CourseWaffleFlag` enabled). The Basic Outcomes Service and Result Service handle grade pass backs. Because we now have two ways to identify a user in LTI 1.1/2.0, we must update the Basic Outcomes Service and Result Service to support both.
Testing these is a little …
> Fix LTI 1.1 Basic Outcomes Service and LTI 2.0 Result Service to Support External User IDs

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/models.py
- lti_consumer/tests/unit/test_models.py
I'm running into two problems with this check when this code is run in edx-exams. Location isn't required on this model so location.course_key may fail but more importantly `database_config_enabled` can only run in the LMS. Checking if location exists first would technically fix this since a location implies this is running in the LMS (for now) but I'm coming to the conclusion that this check should probably not exist here.
All other instances of `database_config_enabled` occur within the lti_xblock.py which is totally fine to call into the LMS compatibility layer but baking this function into the data model feels like something that will catch us again later. The waffle flag already gates the UI behavior, do we really need this check on the model also?
Let know if I'm missing some good …
> fix: remove lms specific waffle check

- README.rst
- docs/basic_outcomes_service.rst
- docs/result_service.rst
This pull request adds manual testing instructions for LTI 1.1/1.2 Basic Outcomes Service 1.0 and LTI 2.0 Result Service 2.0 and references these documents from the main README so that they're discoverable.
> docs: manually testing LTI 1.1 Basic Outcomes Service 1.0 and LTI 2.0 Result Service

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/plugin/compat.py
- lti_consumer/plugin/views.py
This is a temporary solution. We would like to enable PII in an LTI1.3 launch but turning that flag on would allow the tool to grab PII for the entire course roster via NRPS. We have not fully evaluated the privacy concerns if that is allowed. For the time being this platform setting can wholly disable PII over NRPS to avoid the issue.
> feat: adds setting to prevent nrps pii

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/data.py
- lti_consumer/lti_1p3/consumer.py
- lti_consumer/lti_1p3/tests/test_consumer.py
- lti_consumer/lti_xblock.py
- lti_consumer/models.py
- lti_consumer/plugin/views.py
- lti_consumer/static/js/xblock_lti_consumer.js
- lti_consumer/templates/html/student.html
- lti_consumer/tests/test_utils.py
- lti_consumer/tests/unit/test_lti_xblock.py
This pull request fixes a few issues and bugs with sharing personally identifiable information (PII) in LTI launches as well as one bug with the `modal` LTI launch in LTI 1.3.
The follow issues and bugs were resolved in this pull request:
* `username` and `email` are not sent in LTI 1.3 launches
* the PII sharing LTI XBlock fields always appear, regardless of the existence and value of a `CourseAllowPIISharingInLTIFlag`
* `inline` LTI launches did not trigger a PII consent modal
* `modal` LTI launches did not trigger a PII consent modal
* the `modal` LTI launch for LTI 1.3 failed due to differences in the form of the launch URL provided to the Javascript via the XBlock code
* the values returned by `lti_access_to_learners_editable` were not correct, and the values were not being …
> Fix PII Sharing Behavior and Enable PII Sharing in LTI 1.3 Launches and Fix LTI 1.3 Modal Launches

- README.rst
- lti_consumer/lti_1p3/README.md
- lti_consumer/models.py
- lti_consumer/utils.py
Allows independent configuration of the base URL used for LTI API requests and LTI browser flow. This primarily aids local development because we no longer have to tunnel the entire LMS in order to test against the IMS tools. You can use your normal browser steps to login to the LMS and access content without hacking up your settings which can break other parts of the platform.
Testing LTI launches in another service or IDA is particularly problematic right now because we need to tunnel multiple services (LMS + IDA).
This change would also support cases where a service may have a separate URL scheme for backend requests like the OAuth flow versus frontend redirects, which need to make use of specific browser cookies.
> feat: support separate different base urls for UI flow and API callbacks

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/static/js/xblock_lti_consumer.js
This commit fixes a bug in the PII sharing consent dialog.
The bug resulted in bizarre behavior when there were more than one LTI component in a unit. For example, if there were two LTI inline launches in a unit, two "OK" button would appear in a single component, instead of in their respective components. Another example is that clicking the "View resource in a [modal|new] window" buttons under two LTI components resulted in the "OK" and "Cancel" buttons as well as the PII sharing prompt appearing in a single component, instead of in their respective components.
This is because the dialog-container div that is dynamically created in the Javascript was not scoped to the LTI component, so there was a div with a id of "dialog-container" for each component configured to share PII. When …
> Fix bug in rending buttons and message in PII sharing consent dialog.

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/lti_xblock.py
- lti_consumer/plugin/compat.py
`module_render` and `get_module_for_descriptor_internal` were renamed in https://github.com/openedx/edx-platform/pull/31475. This PR fixes imports.
See the testing instructions for https://github.com/openedx/edx-platform/pull/31475
> [BD-13][BB-6926] refactor: fix module-containing imports

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/static/js/xblock_lti_consumer.js
This commit fixes inappropriate instructions displayed when collecting PII sharing consent before an inline LTI launch. Previously, the instructions said, "Click OK to have your [username (and) e-mail address] sent to a 3rd party application. Click Cancel to return to this page without sending your information." The latter sentence does not make sense in the context of an inline launch, because there is no cancel button. This commit modifies the inline PII sharing consent dialog to say, "Click OK to have your [username (and) e-mail address] sent to a 3rd party application.""
> fix: inappropriate instructions for inline PII sharing consent dialog

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/lti_1p3/consumer.py
- lti_consumer/lti_1p3/key_handlers.py
- lti_consumer/lti_1p3/tests/test_key_handlers.py
JIRA: [MST-1853](https://2u-internal.atlassian.net/browse/MST-1853)
This commit adds logging for error cases in the access_token_endpoint view and the key handler classes. This will make it easier to debug issues with requesting or using LTI 1.3 access tokens.
> feat: add logging for access token view and key handlers

- lti_consumer/data.py
- lti_consumer/lti_1p1/consumer.py
- lti_consumer/lti_1p1/tests/test_consumer.py
- lti_consumer/lti_1p3/consumer.py
- lti_consumer/lti_xblock.py
- lti_consumer/plugin/views.py
- lti_consumer/static/js/xblock_lti_consumer.js
- lti_consumer/templates/html/student.html
- lti_consumer/tests/test_utils.py
- lti_consumer/tests/unit/test_lti_xblock.py
This commits adds the ability to share a learner's full name in both LTI 1.1 and LTI 1.3 launches. In LTI 1.1, the full name is sent as the `lis_person_name_full` LTI parameter. In LTI 1.3, the full name is sent as the `name` ID token claim.
The full name corresponds to the learner's name as recorded by the `UserProfile` model in the LMS.
Enabling the transmission of full name in either version of LTI follows the existing pattern for PII sharing. In order for full name to be shared via an LTI launch, the `CourseAllowPIISharingInLTIFlag` configuration model must be enabled for the course, and the `Request user's full name` XBlock field must be enabled in the XBlock describing the particular LTI integration.
Please note that this commit does not add the ability to share a learner's full …
> feat: add full name as a LTI PII field

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/lti_1p1/consumer.py
- lti_consumer/lti_1p3/consumer.py
Typecast `PLATFORM_NAME` to a string to ensure that it can be parsed correctly by Oauth code. This fix will unblock the release of this library in edx-platform, which is currently blocked by failing tests: https://github.com/openedx/edx-platform/pull/32166.
> fix: ensure platform name is string

- lti_consumer/data.py
- lti_consumer/lti_1p3/constants.py
- lti_consumer/lti_1p3/consumer.py
- lti_consumer/lti_1p3/tests/test_consumer.py
- lti_consumer/plugin/views.py
Adds optional support for the proctoring assessment control service (ACS)
Example of how to use this in edx-exams: https://github.com/edx/edx-exams/pull/122
> feat: support assessment control claims

- README.rst
closes #354
Removes from the README.md the incorrect instructions to update only some languages instead of all.
> docs: fix translations update instructions

- CHANGELOG.rst
- lti_consumer/plugin/views.py
A common launch failure is missing/incorrect cookies that cause the user_id to be None. This makes it a lot easier to identify that problem without digging around.
> fix: log user_id on lti launch failure

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/plugin/views.py
Allows for start proctoring message result to be rendered in an iframe. This isn't full support for proctoring inside an iframe there are still issues with rendering our learning MFE this way. This does unblock testing the launch flow at minimum.
> feat: allow proctoring start from iframe

- CHANGELOG.rst
- lti_consumer/lti_xblock.py
- lti_consumer/tests/unit/test_lti_xblock.py
This adds a new warning in Studio for LTI 1.1/1.2 consumer components if the specified `lti_id` is not valid for the current course. It doesn't block you from setting an invalid ID, in case you're setting the ID first in the XBlock, then later in Advanced Settings.
Private-ref: MNG-3638
> [FC-0009] feat: For LTI 1.1, show a warning in Studio if lti_id is not right

- Makefile
- lti_consumer/conf/locale/config.yaml
* Fixes translation extraction and compilation by adding a missing configuration for `ignore_dirs`. JS text extraction is failing because it re-reads its own `public/js/translations` directory. Related to work done in https://github.com/openedx/xblock-lti-consumer/pull/360
* Fixes `make extract_translations` to use `msgcat` instead of `tail`. Related to work done in https://github.com/openedx/xblock-lti-consumer/pull/341
References
----------
This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).
Check the links above for full information about the …
> fix: make extract_translations

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/lti_1p3/consumer.py
- lti_consumer/lti_1p3/tests/test_consumer.py
Allows a basic LtiResourceLinkRequest launch to be performed by the proctoring consumer class. Since it's the parent class this made sense to me versus initializing a different consumer type based on the launch message. Which, would also be hard to implement anyway.
> feat: ProctoringConsumer basic launch request

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/lti_1p3/constants.py
Related to https://github.com/edx/edx-exams/pull/154.
JIRA: https://2u-internal.atlassian.net/jira/software/projects/MST/boards/584?selectedIssue=MST-1961
Description
As of now, the ACS endpoint only supports a flag action. We would also like to support terminate as a way for Proctorio to communicate that they have ended an attempt.
Upon receiving a terminate request, the attempt referenced in the request should be moved to a corresponding status, depending on the reason for termination (reason_code) and incident_severity. The reason_code mappings should be clarified with Proctorio, and the incident_severity should be discussed internally to decide what range of values are considered passing.
Reason codes:
user_submission: move attempt to verified or second_review_required
error: move …
> fix: correct acs actions constant

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/data.py
- lti_consumer/lti_xblock.py
- lti_consumer/plugin/views.py
- lti_consumer/tests/unit/plugin/test_views.py
- lti_consumer/tests/unit/test_lti_xblock.py
This PR adds a feature that allows the LTI consumer XBlock to send custom parameters (including dynamic custom parameters) and extra claims to LTI 1.3 launches.
2. Add LTI custom params template setting:
``` 
LTI_CUSTOM_PARAM_TEMPLATES = {
'test_param': 'django.utils.html:escape'
}
```
3. Add a LTI processors to XBLOCK_SETTINGS (Example: https://github.com/appsembler/tahoe-lti).
4. Create a course and add a LTI 1.3 consumer XBlock.
5. Add custom parameters to the XBlock settings.
```
["test=test", "test_param=${test_param}"] 
``` 
6. Enable the "Send extra parameters" setting. 
7. Go to the live course and execute an LTI 1.3 launch.
8. The custom parameters and extra claims should be present on the https://purl.imsglobal.org/spec/lti/claim/custom claim.
> fix: LTI 1.3 extra claims and custom parameters

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/lti_xblock.py
- lti_consumer/tests/unit/test_lti_xblock.py
This PR adds a fix to the validation of the LTI consumer XBlock custom parameters field. The previously merged PR https://github.com/openedx/xblock-lti-consumer/pull/392 introduced a bug that broke backwards compatible with custom parameters such has: `["next=something?repo=https://github.com/org/repo?folder=/home/user&branch=main"]`. This issue was raised on https://github.com/openedx/xblock-lti-consumer/issues/410.
1. Create a course and add a LTI consumer XBlock.
2. Add custom parameters to the XBlock settings.
```
["next=something?repo=https://github.com/org/repo?folder=/home/user&branch=main"] 
``` 
3. Go to the live course and execute an LTI launch.
4. The custom parameters should be present on the LTI launch data.
> fix: Custom parameters validation

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/api.py
- lti_consumer/lti_1p3/consumer.py
- lti_consumer/models.py
We're seeing some unexpectedly slow execution on launch endpoints. These trace statements will allow us to profile these functions specifically in New Relic.
> feat: add newrelic tracing

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/lti_1p3/consumer.py
- lti_consumer/lti_1p3/key_handlers.py
We're spending over a second initializing the consumer object which slows down every endpoint. If that's our issue it seems like loading these keys is the only potential cause in that code path. Logging each step to confirm.
> feat: additional performance tracing

- .tx/config
- CHANGELOG.rst
- README.rst
- lti_consumer/__init__.py
- lti_consumer/conf/locale/config.yaml
- lti_consumer/lti_xblock.py
Breaking change!
---
This change breaks the Jenkins transifex integration which has been deprecated in favor of the new GitHub Transifex App integration as part of [OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).
*************************************
**This PR depends on https://github.com/openedx/xblock-lti-consumer/pull/452 and contains a cherry-pick from it until that one is merged**
*************************************
Changes
---
Merge timeline
---
This should only be merged after [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification) is fully implemented.
The timing …
> feat!: remove Transifex calls for FC-0012 - OEP-58

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/lti_xblock.py
- lti_consumer/tests/unit/test_lti_xblock.py
Users with accents in their names are unable to use certain LTI tools because we do not send a utf-8 encoded version of their name to the LTI tool. 
This change encodes a user's full name, which is then used in the LTI launch.
> fix: add utf-8 encoding for user fields

- .github/workflows/pypi-publish.yml
It looks like the python version for the pypi publish workflow has been updated for other repos (see https://github.com/openedx/edx-proctoring/pull/1210). 
The publish step is currently not working for xblock-lti-consumer, so checking if this works.
> feat: update python version for pypi

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/lti_xblock.py
- lti_consumer/tests/unit/test_lti_xblock.py
Related to [COSMO-276](https://2u-internal.atlassian.net/browse/COSMO-276).
A user's name is already utf-8 encoded as part of the HTML form used in the LTI launch handler.
> fix: remove utf-8 encoding for full name

- README.rst
- lti_consumer/__init__.py
- lti_consumer/lti_xblock.py
- update lti testing url in the README, as saltire has updated the test URLs.
- add a note in the README to use `norefresh` param, to avoid failures if using more than one same LTI xblocks in the same unit. Details can be viewed here: https://github.com/openedx/xblock-lti-consumer/issues/379
- close #379.
> docs: update saltire LTI URL for testing LTI 1.1/1.2

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/lti_1p3/key_handlers.py
- lti_consumer/lti_1p3/tests/test_consumer.py
- lti_consumer/lti_1p3/tests/test_key_handlers.py
- lti_consumer/lti_1p3/tests/utils.py
- lti_consumer/plugin/views.py
- lti_consumer/tests/unit/plugin/test_proctoring.py
- lti_consumer/tests/unit/plugin/test_views.py
- lti_consumer/tests/unit/plugin/test_views_lti_ags.py
- lti_consumer/tests/unit/plugin/test_views_lti_deep_linking.py
- lti_consumer/tests/unit/plugin/test_views_lti_nrps.py
- lti_consumer/tests/unit/test_lti_xblock.py
- lti_consumer/tests/unit/test_models.py
- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/quality.txt
- requirements/test.txt
**Related ticket**
- https://github.com/openedx/edx-drf-extensions/issues/290
> Replace pyjwkest with pyjwt package

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/lti_1p3/key_handlers.py
- lti_consumer/lti_1p3/tests/test_consumer.py
- lti_consumer/lti_1p3/tests/test_key_handlers.py
- lti_consumer/plugin/views.py
- requirements/quality.in
- requirements/quality.txt
- requirements/test.in
- requirements/test.txt
Changes introduced in v9.13.0 caused LTI 1.3 launches to not function. This was because the `kid` field was missing from both the JWT header sent to the tool, and from the public keyset endpoint. 
This PR adds the `kid` to the JWT header and ensures that the `kid` is also available in the public keyset endpoint. I've also removed some `pyjwkest` related code that is no longer needed.
> fix: ensure that LTI 1.3 launches work

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/lti_xblock.py
- lti_consumer/plugin/compat.py
- lti_consumer/tests/unit/plugin/test_views.py
- lti_consumer/tests/unit/test_lti_xblock.py
- test_settings.py
Part of: https://github.com/openedx/frontend-app-authoring/issues/1514
Private-ref: [FAL-4032](https://tasks.opencraft.com/browse/FAL-4032)
Fixes errors thrown when previewing/editing LTI Consumer blocks in a Libraries v2 context.
To verify the issues fixed here:
1. Ensure that `lti_consumer` is in the list of `LIBRARY_SUPPORTED_BLOCKS` configured for your Authoring MFE.
1. Create a course, section, subsection, unit
2. Edit the course's Advanced Settings to add `lti_consumer` to the Advanced Module List.
3. Add 2 new LTI Consumer blocks to your course unit -- one to test LTI 1.1, and one to test LTI 1.3.
4. Edit the course blocks to configure them accordingly:
- LTI 1.3: see [README#lti-13](https://github.com/openedx/xblock-lti-consumer?tab=readme-ov-file#lti-13)
**Note** Take care to …
>  Allow lti_consumer blocks to be used in Libraries v2 context [FC-0076] 

- CHANGELOG.rst
- lti_consumer/__init__.py
- lti_consumer/lti_1p3/key_handlers.py
- requirements/base.txt
- requirements/ci.txt
- requirements/common_constraints.txt
- requirements/dev.txt
- requirements/pip.txt
- requirements/pip_tools.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/tox.txt
This PR upgrade python requirements and fixes code([failures](https://github.com/openedx/xblock-lti-consumer/actions/runs/13266356476/job/37034706505?pr=531)) after upgrading `pyjwt` from `2.6.0` to `2.10.1`.
> chore: Upgrade Python requirements

- .github/workflows/ci.yml
- CHANGELOG.rst
- Makefile
- lti_consumer/__init__.py
- lti_consumer/lti_1p3/extensions/rest_framework/serializers.py
- lti_consumer/tests/unit/test_models.py
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/pip.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/tox.txt
- setup.py
- tox.ini
In this PR:
- add django 5.2 support
- fix make upgrade command to compile test.txt correctly and Let tox control the Django version for tests, also upgrade requirments again after the fix.
- This will fix this: https://github.com/openedx/xblock-lti-consumer/actions/runs/14445151146/job/40503912866?pr=551
- fix timezone import, as utc attribute was removed in Django 5.0.
- This will fix this: https://github.com/openedx/xblock-lti-consumer/actions/runs/14446482262/job/40508199546?pr=551
- close #549
> feat: add django 5.2 support

- README.rst
The development setup in the README was very outdated. Updating it with latest Tutor dev based instructions and restructured the related content a bit.
> docs: update dev info on README to use Tutor

- lti_consumer/static/js/xblock_lti_consumer.js
This PR removes two calls that append text to the `body` element after an LTI launch is attempted.
These appear to be debug/testing statements and are not part of the LTI launch flow. Removing these avoids injecting the extra markup and has no effect on the core functionality.
Screenshot of the removed output:
> fix: remove confirm dialog result append statements
