openedx/xblock-lti-consumer

lti_consumer/static/js/xblock_lti_consumer.js, lti_consumer/templates/html/lti_iframe.html, lti_consumer/templates/html/student.html
=> PHX-255 Launch LTI provider on modal window open

lti_consumer/lti_consumer.py, lti_consumer/translations/en/LC_MESSAGES/text.po, lti_consumer/utils.py, setup.py
@mattdrayer your initial thoughts here ?
=> asadiqbal08/WL-356: Add I18N support

setup.py
@marcotuts 
https://github.com/edx/xblock-lti-consumer/compare/v1.0.5...v1.0.6
=> Increment setup.py version for release 1.0.6

lti_consumer/lti.py, lti_consumer/lti_consumer.py, lti_consumer/tests/unit/test_lti.py
This is a pull request to add due dates and display names to the current lti parameters.
=> Added display name and due date to LTI Parameters

.tx/config, README.rst, lti_consumer/translations/ar/LC_MESSAGES/text.po, lti_consumer/translations/es_419/LC_MESSAGES/text.po, lti_consumer/translations/fr/LC_MESSAGES/text.po, lti_consumer/translations/he/LC_MESSAGES/text.po, lti_consumer/translations/hi/LC_MESSAGES/text.po, lti_consumer/translations/ko_KR/LC_MESSAGES/text.po, lti_consumer/translations/pt_BR/LC_MESSAGES/text.po, lti_consumer/translations/ru/LC_MESSAGES/text.po, lti_consumer/translations/zh_CN/LC_MESSAGES/text.po, setup.py
This PR added translation files download from transifex and transifex config to support WL-580.
@douglashall could you please review it?
=> ziafazal/WL-580: added translation files and transifex config

setup.py
@mushtaqak @muhammad-ammar please review.
=> bump up version

.travis.yml, lti_consumer/exceptions.py, lti_consumer/lti.py, lti_consumer/lti_consumer.py, lti_consumer/oauth.py, lti_consumer/outcomes.py, lti_consumer/tests/unit/test_lti.py, lti_consumer/tests/unit/test_lti_consumer.py, lti_consumer/tests/unit/test_oauth.py, lti_consumer/tests/unit/test_outcomes.py, lti_consumer/tests/unit/test_utils.py, openedx.yaml, requirements.txt, setup.py, test.py, test_requirements.txt
Updated to run tests on both python 2 and 3.
PROD-774
=> Upgrade to pyhton 3.

.coveragerc, lti_consumer/__init__.py, lti_consumer/apps.py, lti_consumer/lti_1p3/constants.py, lti_consumer/lti_1p3/consumer.py, lti_consumer/lti_consumer.py, lti_consumer/plugin/urls.py, lti_consumer/plugin/views.py, lti_consumer/templates/html/lti_1p3_launch.html, lti_consumer/templates/html/lti_1p3_oidc.html, lti_consumer/templates/html/lti_1p3_studio.html, lti_consumer/templates/html/student.html, lti_consumer/tests/unit/test_lti_1p3_consumer.py, lti_consumer/tests/unit/test_lti_consumer.py, lti_consumer/utils.py, requirements.txt, setup.py
This PR implements a proof-of-concept implementation of the LTI 1.3 standard to the current LTI Block without breaking LTI 1.1 support.
**JIRA tickets**: [TNL-7133 (epic)](https://openedx.atlassian.net/browse/TNL-7133), [TNL-7183](https://openedx.atlassian.net/browse/TNL-7183).
**Sandbox:** TBD (issues provisioning master sandbox).
**Discussions**: 
- Slack: https://openedx.slack.com/archives/CVCD5LACC
**Setup instructions:**
1. Clone this branch on your devstack's `src` folder 
2. Install in LMS and Studio 
```
$ lms-shell
> pip install -e /edx/src/xblock-lti-consumer
```
3. Set up a local tunnel (using `ngrok` or a similar tool) 
4. Set up a tool in the IMS Global reference implementation (https://lti-ri.imsglobal.org/lti/tools/).
1. Create a new course, and …
=> [BD-2] BB-2250: LTI 1.3 base implementation

lti_consumer/lti_1p3/README.md, lti_consumer/lti_1p3/constants.py, lti_consumer/lti_1p3/consumer.py, lti_consumer/lti_1p3/exceptions.py, lti_consumer/lti_1p3/key_handlers.py, lti_consumer/lti_1p3/tests/test_consumer.py, lti_consumer/lti_1p3/tests/test_key_handlers.py, lti_consumer/lti_1p3/tests/utils.py, lti_consumer/lti_consumer.py, lti_consumer/plugin/urls.py, lti_consumer/plugin/views.py, lti_consumer/templates/html/lti_1p3_studio.html, lti_consumer/tests/unit/test_lti_consumer.py, lti_consumer/utils.py
This PR implements the LTI 1.3 Access token endpoint. The new endpoint complies with IMS Global Security framework specification: https://www.imsglobal.org/spec/security/v1p0.
1. Run tests, make sure all pass.
2. Run quality checks.
3. Install and run this in the LMS.
4. Create a new `lti_consumer` block set LTI version to 1.3.
5. Go to https://jwt.io/ and select RS256 on the `ALGORITHM` field.
6. Copy the public key and paste it into the XBlock LTI Tool public key field (make sure that line breaks are encoded to `\n`).
7. Add in `exp` to the example JWT with a long expiry time.
8. Make a request to the token endpoint:
```
curl --request POST \
--url 'http://localhost:18000/api/lti_consumer/v1/token/block-v1:OpenCraft+LTI101+2020_T2+type@lti_consumer+block@efc55c7 …
```
=> [BD-2] BB-2354: Implement Access Token endpoint

Makefile, README.rst, setup.py
https://openedx.atlassian.net/browse/BOM-1674
=> BOM-1674 : Update setup.py for pypi release

requirements/base.txt, requirements/django.txt, requirements/pip_tools.txt, requirements/test.in, requirements/test.txt, requirements/tox.txt, requirements/travis.txt
https://openedx.atlassian.net/browse/BOM-1699
=> Change xblock-sdk installation

lti_consumer/lti.py, lti_consumer/lti_consumer.py, lti_consumer/oauth.py, lti_consumer/outcomes.py, lti_consumer/tests/unit/test_lti.py, lti_consumer/tests/unit/test_lti_consumer.py, lti_consumer/tests/unit/test_oauth.py, lti_consumer/tests/unit/test_outcomes.py, lti_consumer/tests/unit/test_utils.py, setup.py, test.py
Relevant JIRA issue [here](https://openedx.atlassian.net/browse/BOM-1761).
=> Removed deprecated future imports

lti_consumer/lti_1p3/consumer.py, lti_consumer/lti_1p3/tests/test_consumer.py, lti_consumer/utils.py
**Issue:** [BOM-1712](https://openedx.atlassian.net/browse/BOM-1712)
- Removed usages of package `six`.
=> Removed usages of package six

requirements/base.txt, requirements/django.txt, requirements/test.in, requirements/test.txt, requirements/tox.txt, requirements/travis.txt
**Packages removed**
- django-nose
=> [BD-18] remove nose footprints from the project

lti_consumer/lti_1p3/key_handlers.py, lti_consumer/lti_1p3/tests/test_consumer.py, lti_consumer/lti_1p3/tests/test_key_handlers.py, lti_consumer/lti_xblock.py, lti_consumer/tests/unit/test_lti_xblock.py, requirements/base.in, requirements/base.txt, requirements/test.txt, requirements/tox.txt, requirements/travis.txt, setup.py
Relevant JIRA : https://openedx.atlassian.net/browse/BOM-1953
=> BOM-1953 : Replace pycryptodome with pycryptodomex

.travis.yml, Makefile
Attempt to improve CI workflow and separate `tests` and `quality` checks.
=> [BD-24] Improve CI workflow

.gitignore, MANIFEST.in
The setup.py references requirements/base.in, so it needs to be included
in the distribution by naming it in MANIFEST.in
Without this, the installation fails:
```
Processing /ses/xblock-lti-consumer/dist/lti-consumer-xblock-2.3.tar.gz
ERROR: Command errored out with exit status 1:
command: /usr/local/virtualenvs/tmp-a87c65121b61aeb1/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/j2/gr3cj3jn63s5q8g3bjvw57hm0000gp/T/pip-req-build-eivs709n/setup.py'"'"'; __file__='"'"'/private/var/folders/j2/gr3cj3jn63s5q8g3bjvw57hm0000gp/T/pip-req-build-eivs709n/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base …
```
=> Fix the installation

docs/decisions/0002-lti-1p3-variables.rst
This PR add's an ADR to list the LTI 1.3 integration variable mapping and the reasoning behind each value.
**Reviewers:**
=> [BD-2][TNL-7315] BB-2612: Add ADR for LTI 1.3 variable definition

docs/decisions/0003-lti-1p3-score-linking.rst
This PR introduces the Score linking decisions related to grading when using LTI 1.3 tools.
**Reviewers:**
=> [BD-24][TNL-7647] BB-3128: Score linking ADR

lti_consumer/api.py, lti_consumer/templates/html/lti_1p3_studio.html, lti_consumer/tests/unit/test_api.py
@giovannicimolin is it OK to show this as formatted JSON?
=> fix: show the configuration as nicely formatted JSON

README.rst, lti_consumer/lti_1p3/consumer.py, setup.py
This PR updates the documentation related to the LTI-AGS service and adds a missing version bump.
**Reviewer:**
=> [BD-24] Version bump and update docs.

README.rst, docs/decisions/0004-lti-advantage-nrps.rst, lti_consumer/lti_xblock.py, lti_consumer/plugin/compat.py, lti_consumer/plugin/views.py, lti_consumer/templates/html/lti_1p3_studio.html, lti_consumer/tests/unit/test_lti_xblock.py, lti_consumer/translations/en/LC_MESSAGES/text.po, lti_consumer/utils.py, setup.py, test_settings.py
This PR simplifies the name of the LTI fields: they are now matching names from other LMS's. 
It also enables LTI 1.3 and Advantage features and removes unnecessary feature flags. 
Reviewers:
=> [BD-24][BB-4204] Flag cleanup and minor fixes

lti_consumer/__init__.py, setup.py
Description:
Standardize the placement of version number
=> Standardize version number placement

lti_consumer/__init__.py
this will cause the pypi release to work
=> chore: update version

docs/decisions/0006-pluggable-lti-configuration.rst
This ADR describes the implementation of pluggable and reusable LTI configurations.
=> BB-5051: Pluggable/reusable LTI configuration

.github/workflows/upgrade-python-requirements.yml, requirements/pip_tools.txt
[MST-1485](https://openedx.atlassian.net/browse/MST-1485)
=> chore: update requirements upgrade automation

CHANGELOG.rst, lti_consumer/__init__.py
=> feat: changelog and release for new URL settings

CHANGELOG.rst, lti_consumer/__init__.py, lti_consumer/translations/ar/LC_MESSAGES/text.po, lti_consumer/translations/es_419/LC_MESSAGES/text.po, lti_consumer/translations/fr/LC_MESSAGES/text.po, lti_consumer/translations/he/LC_MESSAGES/text.po, lti_consumer/translations/hi/LC_MESSAGES/text.po, lti_consumer/translations/ko_KR/LC_MESSAGES/text.po, lti_consumer/translations/pt_BR/LC_MESSAGES/text.po, lti_consumer/translations/ru/LC_MESSAGES/text.po, lti_consumer/translations/zh_CN/LC_MESSAGES/text.po
This repo isn't hooked up to a scheduled job so `tx pull` was run manually
=> chore: update translations

CHANGELOG.rst, lti_consumer/__init__.py, lti_consumer/translations/ar/LC_MESSAGES/text.po, lti_consumer/translations/es_419/LC_MESSAGES/text.po, lti_consumer/translations/fr/LC_MESSAGES/text.po, lti_consumer/translations/he/LC_MESSAGES/text.po, lti_consumer/translations/hi/LC_MESSAGES/text.po, lti_consumer/translations/ko_KR/LC_MESSAGES/text.po, lti_consumer/translations/pt_BR/LC_MESSAGES/text.po, lti_consumer/translations/ru/LC_MESSAGES/text.po, lti_consumer/translations/zh_CN/LC_MESSAGES/text.po
Pull down updated translations from transifex, this includes the new strings generated by #353
=> feat: pull translations

CHANGELOG.rst, lti_consumer/__init__.py, lti_consumer/plugin/compat.py
Fixes compatibility issue with recent LMS changes to refactor item/module/block/descriptor terminology.
=> fix: lms compatibility with descriptor->block rename

CHANGELOG.rst, lti_consumer/__init__.py, lti_consumer/plugin/views.py, lti_consumer/templates/html/lti_start_assessment.html, lti_consumer/tests/unit/plugin/test_proctoring.py
[MST-1859](https://2u-internal.atlassian.net/browse/MST-1859)
Screenshot of start assessment html:
=> feat: return html start assessment

CHANGELOG.rst, lti_consumer/__init__.py, lti_consumer/lti_1p3/constants.py, lti_consumer/lti_1p3/consumer.py, lti_consumer/lti_1p3/tests/test_consumer.py
Relevant ticket: [MST-1897](https://2u-internal.atlassian.net/browse/MST-1897)
=> feat: only add acs scope when proctoring

CHANGELOG.rst, lti_consumer/__init__.py, lti_consumer/plugin/compat.py
Fix call to `get_block_for_descriptor_internal` that was removed with https://github.com/openedx/edx-platform/pull/32420
=> fix: removed get_block_for_descriptor_internal call

CHANGELOG.rst, README.rst, lti_consumer/__init__.py, lti_consumer/lti_xblock.py, lti_consumer/plugin/views.py, lti_consumer/templates/html/lti_launch_error.html, lti_consumer/tests/unit/plugin/test_views.py, lti_consumer/tests/unit/test_lti_xblock.py
Ticket: [MST-1931](https://2u-internal.atlassian.net/browse/MST-1931)
=> feat: added error msg to launch error template

.github/workflows/ci.yml, CHANGELOG.rst, lti_consumer/__init__.py, lti_consumer/admin.py, tox.ini
- Added support for django42
- Issue: https://github.com/edx/upgrades/issues/176
=> fix: Added support for django 42

CHANGELOG.rst, lti_consumer/__init__.py
Bumping the release version so I can trigger a new release workflow.
=> fix: create new release version

lti_consumer/models.py
This class was just missing an annotation.
=> docs: Add PII annotation

README.rst, lti_consumer/lti_xblock.py
ref: https://github.com/openedx/edx-documentation/issues/2339
=> docs: Update outdated link target URLs

lti_consumer/tests/unit/test_lti_xblock.py, requirements/base.in, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/quality.txt, requirements/test.txt
Removed pyjwkest from the base requriements file
=> fix!: Removal of pyjwkest dependency
